### ISSUE TITLE
Unable to build rb-sys with clang 16 due to bindgen issue

### ISSUE THREAD

**Issue by wfchandler** [oxidize-rb/rb-sys#198]
When attempting to build `rb-sys` on a system using clang 16.0, bindgen fails with the error below. This appears to be due to https://github.com/rust-lang/rust-bindgen/issues/2312, which was fixed with bindgen v0.62.

Whenever [the bindgen version is bumped](https://github.com/oxidize-rb/rb-sys/issues/175) this problem should be fixed, but I haven't found a workaround in the meantime for systems with clang 16.

I'm running into this myself after upgrading to Fedora 38.

```
  --- stderr
  Using bindgen with clang args: ["-I/home/wfc/.local/share/rtx/installs/ruby/3.0.5/include/ruby-3.0.0", "-I/home/wfc/.local/share/rtx/installs/ruby/3.0.5/include/ruby-3.0.0/x86_64-linux", "-fms-extensions", "-O3", "-ggdb3", "-Wall", "-Wextra", "-Wdeprecated-declarations", "-Wduplicated-cond", "-Wimplicit-function-declaration", "-Wimplicit-int", "-Wmisleading-indentation", "-Wpointer-arith", "-Wwrite-strings", "-Wimplicit-fallthrough=0", "-Wmissing-noreturn", "-Wno-cast-function-type", "-Wno-constant-logical-operand", "-Wno-long-long", "-Wno-missing-field-initializers", "-Wno-overlength-strings", "-Wno-packed-bitfield-compat", "-Wno-parentheses-equality", "-Wno-self-assign", "-Wno-tautological-compare", "-Wno-unused-parameter", "-Wno-unused-value", "-Wsuggest-attribute=format", "-Wsuggest-attribute=noreturn", "-Wunused-variable", "-I/home/wfc/.local/share/rtx/installs/ruby/3.0.5/include"]
...
  thread 'main' panicked at '"__atomic_wide_counter_struct_(unnamed_at_/usr/include/bits/atomic_wide_counter_h_28_3)" is not a valid Ident', /home/wfc/.local/share/rtx/installs/rust/1.68.2/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/fallback.rs:811:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
     2: proc_macro2::fallback::validate_ident
     3: proc_macro2::fallback::Ident::_new
     4: proc_macro2::fallback::Ident::new
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: bindgen::ir::context::BindgenContext::rust_ident_raw
     8: bindgen::ir::context::BindgenContext::rust_ident
     9: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    10: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    11: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    12: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    13: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    14: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    15: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
    16: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    17: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    18: bindgen::codegen::codegen::{{closure}}
    19: bindgen::ir::context::BindgenContext::gen
    20: bindgen::codegen::codegen
    21: bindgen::Bindings::generate
    22: bindgen::Builder::generate
    23: rb_sys_build::bindings::generate
    24: build_script_main::main
    25: core::ops::function::FnOnce::call_once
```

**Comment by ianks** [comment]
Yeah... this is a very unfortunate issue that we can't solve without breaking our `msrv` (which is now 1.54).

My plan was to batch this breaking change with `rb-sys` 1.0, but we may have to break our `msrv` policy if it's causing more harm than good.

Have you tried [`libclang-rb`](https://github.com/oxidize-rb/rb-sys/tree/e0a1192fb4ac8b53d72debe6ca5acd02e564c705/gem#libclang-issues)? I've never tried on Fedora, so I'd be curious to see if it works. If not, we'll figure something else out.

**Comment by wfchandler** [comment]
@ianks switching the the `libclang` gem worked on this machine, thanks!  I was having some linking problems with it on other hosts that had static copy of `libruby` installed.
